# Generated by Django 5.1.5 on 2025-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('sale_percentage', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
