# Generated by Django 5.1.5 on 2025-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promocodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
