# Generated by Django 5.1.5 on 2025-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_promocodes_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='summarizes_with_other_sales',
            field=models.BooleanField(default=False),
        ),
    ]
