# Generated by Django 5.1.5 on 2025-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promocodes_summarizes_with_other_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cashback_from',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=7),
        ),
    ]
