# Generated by Django 5.1.5 on 2025-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_cashback_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_access_from', models.DecimalField(decimal_places=2, default=300, max_digits=7)),
                ('cashback_percentage', models.IntegerField(default=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_cashback',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cashback_from',
        ),
    ]
