# Generated by Django 5.1.5 on 2025-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_storebase_remove_products_product_cashback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebase',
            name='name',
            field=models.CharField(default='Admin', max_length=20, unique=True),
        ),
    ]
