# Generated by Django 5.1.5 on 2025-02-03 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_storebase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebase',
            name='cashback_access_from',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
