# Generated by Django 5.1.5 on 2025-02-05 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_storebase_cashback_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='sale_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
