# Generated by Django 5.1.6 on 2025-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
