# Generated by Django 5.1.6 on 2025-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='lightning',
            field=models.CharField(choices=[('darkness', 'Darkness'), ('moderate', 'Moderate'), ('daylight', 'Daylight')], default='Moderate', max_length=8),
        ),
    ]
