# Generated by Django 5.1.6 on 2025-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plants_lightning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
