# Generated by Django 5.1.6 on 2025-02-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plants_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
