# Generated by Django 5.1.6 on 2025-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diary_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
