# Generated by Django 5.1.6 on 2025-02-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibits',
            name='category',
        ),
        migrations.AddField(
            model_name='exhibits',
            name='category',
            field=models.ManyToManyField(to='api.categories'),
        ),
    ]
