# Generated by Django 5.1.6 on 2025-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exhibits_category_exhibits_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibits',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='exhibits/'),
        ),
    ]
