# Generated by Django 5.1.6 on 2025-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exhibits_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibits',
            name='photo',
            field=models.ImageField(upload_to='exhibits/'),
        ),
    ]
